import { Link } from 'react-router-dom'
import {
  ArrowRight,
  BarChart3,
  Braces,
  Cpu,
  Database,
  Filter,
  Layers,
  Ruler,
  ScanLine,
  Waves,
} from 'lucide-react'

// Numbers below are produced by `python ml/training/train.py` and stored in
// ml/evaluation/metrics.json — regenerate them any time; do not edit by hand.
const METRICS = {
  datasetImages: 2712,
  classes: 9,
  train: 1898,
  validation: 407,
  test: 407,
  featureDim: 1836,
  accuracy: 80.34,
  f1Macro: 80.83,
  precision: 80.64,
  recall: 81.23,
  latencyMean: 36.9,
  latencyP95: 53.0,
  modelSizeMb: 4.51,
}

const PIPELINE = [
  { icon: ScanLine, title: 'Segmentation', text: 'HSV leaf mask + morphology isolates the leaf and drops the background.' },
  { icon: Waves, title: 'Denoising', text: 'A 5x5 Gaussian blur suppresses JPEG and sensor noise before gradients.' },
  { icon: Layers, title: 'Color & texture', text: 'H/S/V histograms, channel statistics and uniform LBP describe coloration and lesion texture.' },
  { icon: Ruler, title: 'Shape gradients', text: 'HOG over the segmented leaf captures spots, rings and lesion edges.' },
  { icon: Filter, title: 'Scaling + PCA', text: 'Features are standardized and reduced to 95% variance before classification.' },
  { icon: Cpu, title: 'Classifier', text: 'Random Forest (300 trees) — the validation winner over SVM-RBF and Logistic Regression.' },
]

const VALIDATION = [
  { model: 'Logistic Regression', accuracy: 69.53, f1: 70.26 },
  { model: 'SVM (RBF)', accuracy: 71.74, f1: 72.50 },
  { model: 'Random Forest', accuracy: 73.46, f1: 73.71 },
]

const STACK = [
  { icon: Braces, title: 'Frontend', items: 'React 18, Vite, Tailwind CSS, React Router, Recharts, Axios, Vitest' },
  { icon: Cpu, title: 'Backend', items: 'Python, FastAPI, Uvicorn, Pydantic v2, pytest' },
  { icon: BarChart3, title: 'Machine Learning', items: 'OpenCV, scikit-learn, NumPy, pandas, matplotlib, seaborn, joblib' },
  { icon: Database, title: 'Data & Ops', items: 'MongoDB, Docker, Docker Compose, GitHub Actions CI' },
]

export default function About() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16">
      <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
        About LeafGuard AI
      </h1>
      <p className="mt-4 leading-relaxed text-slate-600">
        LeafGuard AI is an end-to-end computer-vision product that detects plant diseases from a
        single leaf photo. It bundles a classical ML pipeline trained on the public{' '}
        <a
          className="font-medium text-leaf-700 hover:underline"
          href="https://github.com/spMohanty/PlantVillage-Dataset"
          target="_blank"
          rel="noreferrer"
        >
          PlantVillage
        </a>{' '}
        dataset with a FastAPI service, a React dashboard, MongoDB-backed history and full Docker
        support — built the way a real product would be, not a one-off notebook.
      </p>

      {/* ---- pipeline ---- */}
      <h2 className="mt-12 text-2xl font-bold text-slate-900">How the analysis works</h2>
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        {PIPELINE.map((step, index) => (
          <div key={step.title} className="card flex gap-4 p-5">
            <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-leaf-100 font-bold text-leaf-700">
              {index + 1}
            </span>
            <div>
              <h3 className="font-semibold text-slate-900">{step.title}</h3>
              <p className="mt-1 text-sm leading-relaxed text-slate-500">{step.text}</p>
            </div>
          </div>
        ))}
      </div>

      {/* ---- measured results ---- */}
      <h2 className="mt-12 text-2xl font-bold text-slate-900">Measured performance</h2>
      <p className="mt-2 text-sm text-slate-500">
        Every number on this page is generated by the training pipeline (ml/training/train.py →
        ml/evaluation/metrics.json) on a held-out test split — nothing is estimated by hand.
      </p>

      <div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">
        {[
          { label: 'Test accuracy', value: `${METRICS.accuracy}%` },
          { label: 'F1 (macro)', value: `${METRICS.f1Macro}%` },
          { label: 'Avg. latency', value: `${METRICS.latencyMean} ms` },
          { label: 'Model size', value: `${METRICS.modelSizeMb} MB` },
        ].map((stat) => (
          <div key={stat.label} className="card p-4 text-center">
            <p className="text-2xl font-extrabold text-leaf-700">{stat.value}</p>
            <p className="mt-1 text-xs font-semibold uppercase tracking-wide text-slate-400">
              {stat.label}
            </p>
          </div>
        ))}
      </div>

      <div className="card mt-6 overflow-x-auto p-5">
        <h3 className="font-semibold text-slate-900">Model comparison (validation split)</h3>
        <table className="mt-3 w-full text-sm" data-testid="model-comparison-table">
          <thead>
            <tr className="border-b border-slate-100 text-left text-xs uppercase tracking-wide text-slate-400">
              <th className="py-2 font-semibold">Model</th>
              <th className="py-2 font-semibold">Accuracy</th>
              <th className="py-2 font-semibold">F1 (macro)</th>
            </tr>
          </thead>
          <tbody>
            {VALIDATION.map((row) => (
              <tr key={row.model} className="border-b border-slate-50">
                <td className="py-2.5 font-medium text-slate-700">
                  {row.model}
                  {row.model === 'Random Forest' && (
                    <span className="ml-2 rounded-full bg-leaf-100 px-2 py-0.5 text-xs font-semibold text-leaf-700">
                      selected
                    </span>
                  )}
                </td>
                <td className="py-2.5 tabular-nums text-slate-600">{row.accuracy.toFixed(2)}%</td>
                <td className="py-2.5 tabular-nums text-slate-600">{row.f1.toFixed(2)}%</td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="mt-3 text-xs leading-relaxed text-slate-400">
          Final test-split metrics ({METRICS.test} held-out images): accuracy {METRICS.accuracy}% ·
          precision (macro) {METRICS.precision}% · recall (macro) {METRICS.recall}% · F1 (macro){' '}
          {METRICS.f1Macro}%. Features: {METRICS.featureDim}-D color/texture/gradient vector.
          Dataset: {METRICS.datasetImages} images across {METRICS.classes} classes ({METRICS.train}/
          {METRICS.validation}/{METRICS.test} train/val/test).
        </p>
      </div>

      <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-relaxed text-amber-800">
        <strong>Honest findings.</strong> On this dataset the preprocessing ablation (with vs.
        without denoising + segmentation) changed test accuracy by 0.00 pp — PlantVillage images are
        already tightly cropped with mostly uniform backgrounds, so background removal adds little
        here. We keep segmentation because it makes the model robust to real-world photos with
        cluttered backgrounds, and we report the null result rather than hiding it. Classical
        features also plateau around 80%, which is exactly why the model service is abstracted for a
        future CNN upgrade.
      </div>

      {/* ---- stack ---- */}
      <h2 className="mt-12 text-2xl font-bold text-slate-900">Tech stack</h2>
      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        {STACK.map((group) => (
          <div key={group.title} className="card p-5">
            <div className="flex items-center gap-2.5">
              <group.icon className="h-4 w-4 text-leaf-600" />
              <h3 className="font-semibold text-slate-900">{group.title}</h3>
            </div>
            <p className="mt-2 text-sm leading-relaxed text-slate-500">{group.items}</p>
          </div>
        ))}
      </div>

      <div className="mt-12 text-center">
        <Link to="/predict" className="btn-primary !px-7 !py-3 !text-base">
          Analyze a Leaf <ArrowRight className="h-4 w-4" />
        </Link>
      </div>
    </div>
  )
}
